# Reddit API credentials
REDDIT_CLIENT_ID = 'mCr9_EBgscaYHZNVSCoY8w'
REDDIT_CLIENT_SECRET = 'cM24xQWt6gNluGFf6aLGY_qM7YzX3Q'
REDDIT_USER_AGENT = 'python:GPTBot:v1.0 (by /u/RedditGPTBot)'
REDDIT_USERNAME = 'RedditGPTBot'
REDDIT_PASSWORD = 'nLDeon7k2aske2j$'

# OpenAI API credentials
OPENAI_API_KEY = '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'